# Generated by Django 6.1.1 on 2026-09-22 03:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeDiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('min_quantity', models.PositiveIntegerField(help_text='Número mínimo de unidades en el carrito para aplicar.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad mínima')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Entre 0 y 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje de descuento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Regla de descuento por volumen',
                'verbose_name_plural': 'Reglas de descuento por volumen',
                'ordering': ['min_quantity'],
            },
        ),
    ]
