# Generated by Django 6.1.1 on 2026-09-22 12:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('category', models.CharField(choices=[('arriendo', 'Arriendo'), ('servicios', 'Servicios públicos'), ('nomina', 'Nómina'), ('marketing', 'Marketing'), ('logistica', 'Logística / envíos'), ('insumos', 'Insumos'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('supplier', models.CharField(max_length=150, verbose_name='Proveedor')),
                ('number', models.CharField(max_length=60, verbose_name='Número de factura')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Factura de proveedor',
                'verbose_name_plural': 'Facturas de proveedor',
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'number'), name='unique_supplier_invoice')],
            },
        ),
    ]
