# Generated by Django 6.1.1 on 2026-09-22 03:39

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('reference', models.CharField(default=apps.orders.models.generate_order_reference, editable=False, max_length=20, unique=True, verbose_name='Referencia')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('customer_id_number', models.CharField(max_length=20, verbose_name='Cédula')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Dirección de envío')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('data_processing_accepted', models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos')),
                ('data_processing_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subtotal')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Porcentaje de descuento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto de descuento')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo de envío')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado'), ('error', 'Error')], default='pendiente', max_length=12, verbose_name='Estado de pago')),
                ('fulfillment_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=16, verbose_name='Estado de envío')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado el')),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=64, verbose_name='ID de transacción WOMPI')),
                ('payment_method', models.CharField(blank=True, max_length=40, verbose_name='Método de pago')),
                ('discount_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.volumediscountrule', verbose_name='Regla de descuento aplicada')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre (snapshot)')),
                ('product_sku', models.CharField(blank=True, max_length=40, verbose_name='SKU (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio unitario')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total de línea')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de pedido',
                'verbose_name_plural': 'Ítems de pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference'], name='orders_orde_referen_cf3026_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
    ]
