# Generated by Django 6.1.1 on 2026-09-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('orders', '0002_webhookevent_order_email_sent_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Se marca automáticamente si hubo un problema al confirmar el pago. Desmárcalo cuando el caso esté resuelto.', verbose_name='Requiere revisión'),
        ),
        migrations.AddField(
            model_name='order',
            name='review_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de revisión'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['needs_review'], name='orders_orde_needs_r_0e1a7b_idx'),
        ),
    ]
