# Generated by Django 6.1.1 on 2026-09-23 22:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Huella de idempotencia'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo unitario (snapshot)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado'), ('error', 'Error'), ('expirado', 'Expirado')], default='pendiente', max_length=12, verbose_name='Estado de pago'),
        ),
    ]
