# Generated by Django 6.1.1 on 2026-09-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_expired_fingerprint_unit_cost'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_referen_cf3026_idx',
        ),
    ]
