# Generated by Django 6.1.1 on 2026-09-22 03:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug (URL)')),
                ('brand', models.CharField(blank=True, default='BULLCULTURE', max_length=100, verbose_name='Marca')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='SKU')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('goal', models.CharField(blank=True, choices=[('ganar_masa', 'Ganar masa muscular'), ('fuerza', 'Fuerza'), ('definicion', 'Definición'), ('energia', 'Energía / pre-entreno'), ('recuperacion', 'Recuperación'), ('salud', 'Salud y bienestar'), ('perdida_peso', 'Pérdida de peso')], help_text='Objetivo principal (para el filtro del catálogo).', max_length=20, verbose_name='Objetivo')),
                ('presentation', models.CharField(blank=True, help_text='Ej.: 1 kg (30 servicios), 60 cápsulas.', max_length=80, verbose_name='Presentación')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de venta')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costo unitario (para rentabilidad, módulo de contabilidad).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='Umbral de stock bajo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('lot_number', models.CharField(max_length=60, verbose_name='Número de lote')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de recepción')),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo por unidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Texto alternativo')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'goal'], name='catalog_pro_is_acti_da1f66_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('product', 'lot_number'), name='unique_lot_per_product'),
        ),
    ]
