# Generated by Django 6.1.1 on 2026-09-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_slug_2b1eb6_idx',
        ),
    ]
